name: BetterSurvival
version: '${version}'
main: me.rexe0.bettersurvival.BetterSurvival
api-version: '26.1'
load: STARTUP
commands:
  bettersurvivalreload:
    description: Reloads the config
    usage: /bettersurvivalreload