name: BetterSurvival
version: '${project.version}'
main: me.rexe0.bettersurvival.BetterSurvival
api-version: '1.21'
load: STARTUP
commands:
  bettersurvivalreload:
    description: Reloads the config
    usage: /bettersurvivalreload